nelmio_api_doc:
    documentation:
        info:
            title: BileMo Catalog-API
            description: Built for you our lovely customers/partners, it enable you to access our phone catalog!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
